"""
Report exporter for CloudGuard AI.
Generates Markdown and PDF analysis reports from a finding + analysis dict.
"""
import io
from datetime import datetime


def to_markdown(finding: dict, result: dict) -> str:
    """Return a full Markdown report string for a finding + analysis."""
    now = datetime.now().strftime("%Y-%m-%d %H:%M UTC")
    title = finding.get("Title", "Unknown Finding")
    sev = finding.get("Severity", {}).get("Label", "UNKNOWN")
    resource = (finding.get("Resources") or [{}])[0].get("Id", "—")
    finding_id = finding.get("Id", "—")

    priority = result.get("priority", "—")
    tldr = result.get("tldr", "—")
    plain = result.get("plain_english", "—")
    why = result.get("why_it_matters", "—")
    impact = result.get("business_impact", {})
    fix_steps = result.get("fix_steps", [])
    frameworks = result.get("compliance_frameworks", [])

    lines = [
        f"# CloudGuard AI — Security Finding Report",
        f"",
        f"> Generated: {now}",
        f"",
        f"---",
        f"",
        f"## {title}",
        f"",
        f"| Field | Value |",
        f"|-------|-------|",
        f"| **Severity** | {sev} |",
        f"| **Priority** | {priority} |",
        f"| **Resource** | `{resource[:100]}` |",
        f"| **Finding ID** | `{finding_id[:60]}` |",
        f"",
        f"---",
        f"",
        f"## TL;DR",
        f"",
        f"> {tldr}",
        f"",
        f"## What Happened",
        f"",
        plain,
        f"",
        f"## Why It Matters",
        f"",
        why,
        f"",
        f"## Business Impact",
        f"",
        f"| Area | Detail |",
        f"|------|--------|",
        f"| 🗄️ Data Risk | {impact.get('data_risk', '—')} |",
        f"| 💰 Financial Risk | {impact.get('financial_risk', '—')} |",
        f"| ⚖️ Compliance Risk | {impact.get('compliance_risk', '—')} |",
        f"",
    ]

    if fix_steps:
        lines += [f"## Remediation Steps", f""]
        for i, step in enumerate(fix_steps, 1):
            lines.append(f"### Step {i}: {step.get('step', '')}")
            if step.get("cli_command"):
                lines.append(f"")
                lines.append("```bash")
                lines.append(step["cli_command"])
                lines.append("```")
            lines.append(f"")

    if frameworks:
        lines += [
            f"## Compliance Frameworks",
            f"",
            ", ".join(f"`{f}`" for f in frameworks),
            f"",
        ]

    lines += [
        f"---",
        f"",
        f"*Report generated by [CloudGuard AI](https://github.com/samadmd786/cloudguard)*",
    ]

    return "\n".join(lines)


def to_pdf(finding: dict, result: dict) -> bytes:
    """
    Return a PDF report as bytes.
    Uses fpdf2 — no system dependencies required.
    """
    from fpdf import FPDF

    title = finding.get("Title", "Unknown Finding")
    sev = finding.get("Severity", {}).get("Label", "UNKNOWN")
    resource = (finding.get("Resources") or [{}])[0].get("Id", "-")[:80]
    now = datetime.now().strftime("%Y-%m-%d %H:%M UTC")

    priority = result.get("priority", "-")
    tldr = result.get("tldr", "-")
    plain = result.get("plain_english", "-")
    why = result.get("why_it_matters", "-")
    impact = result.get("business_impact", {})
    fix_steps = result.get("fix_steps", [])
    frameworks = result.get("compliance_frameworks", [])

    SEV_COLORS = {
        "CRITICAL": (248, 81, 73),
        "HIGH":     (240, 136, 62),
        "MEDIUM":   (227, 179, 65),
        "LOW":      (63, 185, 80),
    }
    accent = SEV_COLORS.get(sev, (99, 179, 255))

    pdf = FPDF()
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()
    pdf.set_margins(20, 20, 20)

    # Header bar
    pdf.set_fill_color(13, 27, 64)
    pdf.rect(0, 0, 210, 28, "F")
    pdf.set_text_color(99, 179, 255)
    pdf.set_font("Helvetica", "B", 16)
    pdf.set_y(8)
    pdf.cell(0, 10, "CloudGuard AI - Security Finding Report", align="C")
    pdf.set_text_color(100, 116, 139)
    pdf.set_font("Helvetica", "", 9)
    pdf.set_y(18)
    pdf.cell(0, 6, f"Generated: {now}", align="C")
    pdf.ln(18)

    # Severity badge
    r, g, b = accent
    pdf.set_fill_color(r, g, b)
    pdf.set_text_color(255, 255, 255)
    pdf.set_font("Helvetica", "B", 10)
    pdf.cell(28, 7, f"  {sev}  ", fill=True, align="C")
    pdf.set_text_color(30, 40, 60)
    pdf.ln(10)

    # Title
    pdf.set_font("Helvetica", "B", 14)
    pdf.set_text_color(15, 23, 42)
    pdf.multi_cell(0, 8, title)
    pdf.ln(2)

    # Metadata row
    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(100, 116, 139)
    pdf.multi_cell(0, 6, f"Priority: {priority}   |   Resource: {resource}")
    pdf.ln(10)

    def section(heading: str):
        pdf.set_font("Helvetica", "B", 10)
        pdf.set_text_color(*accent)
        pdf.cell(0, 6, heading.upper())
        pdf.set_draw_color(*accent)
        pdf.line(20, pdf.get_y() + 6, 190, pdf.get_y() + 6)
        pdf.ln(8)
        pdf.set_text_color(30, 40, 60)
        pdf.set_font("Helvetica", "", 10)

    # TL;DR
    section("TL;DR")
    pdf.set_fill_color(240, 245, 255)
    pdf.multi_cell(0, 6, tldr.replace("—", "-"), fill=True)
    pdf.ln(6)

    # What happened
    section("What Happened")
    pdf.multi_cell(0, 6, plain.replace("—", "-"))
    pdf.ln(6)

    # Why it matters
    section("Why It Matters")
    pdf.multi_cell(0, 6, why.replace("—", "-"))
    pdf.ln(6)

    # Business impact
    section("Business Impact")
    for label, key in [("Data Risk", "data_risk"), ("Financial Risk", "financial_risk"), ("Compliance Risk", "compliance_risk")]:
        pdf.set_font("Helvetica", "B", 9)
        pdf.cell(40, 6, f"{label}:")
        pdf.set_font("Helvetica", "", 9)
        pdf.multi_cell(0, 6, impact.get(key, "-").replace("—", "-"))
    pdf.ln(4)

    # Remediation
    if fix_steps:
        section("Remediation Steps")
        for i, step in enumerate(fix_steps, 1):
            pdf.set_font("Helvetica", "B", 10)
            step_text = f"Step {i}: {step.get('step', '')}".replace("—", "-")
            pdf.multi_cell(0, 6, step_text)
            if step.get("cli_command"):
                pdf.set_fill_color(230, 235, 245)
                pdf.set_font("Courier", "", 8)
                pdf.multi_cell(0, 5, step["cli_command"], fill=True)
            pdf.ln(3)

    # Compliance
    if frameworks:
        section("Compliance Frameworks")
        pdf.set_font("Helvetica", "", 10)
        pdf.cell(0, 6, "  ".join(frameworks))
        pdf.ln(8)

    # Footer
    pdf.set_text_color(150, 160, 180)
    pdf.set_font("Helvetica", "I", 8)
    pdf.cell(0, 6, "Report generated by CloudGuard AI - github.com/samadmd786/cloudguard", align="C")

    return bytes(pdf.output())
