"""
Report exporter for CloudGuard AI.
Generates Markdown analysis reports from a finding + analysis dict.
"""
from datetime import datetime, timezone


def to_markdown(finding: dict, result: dict) -> str:
    """
    Generate a formatted Markdown report from an analyzed finding.

    Combines the raw finding metadata (ID, Resource, Severity) with the
    Claude-generated analysis (TL;DR, remediation steps) into a readable
    Markdown document suitable for Jira, GitHub Issues, or Wikis.

    Args:
        finding (dict): The raw AWS Security Hub finding.
        result (dict): The structured JSON response from Claude.

    Returns:
        str: The complete, formatted Markdown report as a string.
    """
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    title = finding.get("Title", "Unknown Finding")
    sev = finding.get("Severity", {}).get("Label", "UNKNOWN")
    resource = (finding.get("Resources") or [{}])[0].get("Id", "—")
    finding_id = finding.get("Id", "—")

    priority = result.get("priority", "—")
    tldr = result.get("tldr", "—")
    plain = result.get("plain_english", "—")
    why = result.get("why_it_matters", "—")
    impact = result.get("business_impact", {})
    fix_steps = result.get("fix_steps", [])
    frameworks = result.get("compliance_frameworks", [])

    lines = [
        f"# CloudGuard AI — Security Finding Report",
        f"",
        f"> Generated: {now}",
        f"",
        f"---",
        f"",
        f"## {title}",
        f"",
        f"| Field | Value |",
        f"|-------|-------|",
        f"| **Severity** | {sev} |",
        f"| **Priority** | {priority} |",
        f"| **Resource** | `{resource[:100]}` |",
        f"| **Finding ID** | `{finding_id[:60]}` |",
        f"",
        f"---",
        f"",
        f"## TL;DR",
        f"",
        f"> {tldr}",
        f"",
        f"## What Happened",
        f"",
        plain,
        f"",
        f"## Why It Matters",
        f"",
        why,
        f"",
        f"## Business Impact",
        f"",
        f"| Area | Detail |",
        f"|------|--------|",
        f"| 🗄️ Data Risk | {impact.get('data_risk', '—')} |",
        f"| 💰 Financial Risk | {impact.get('financial_risk', '—')} |",
        f"| ⚖️ Compliance Risk | {impact.get('compliance_risk', '—')} |",
        f"",
    ]

    if fix_steps:
        lines += [f"## Remediation Steps", f""]
        for i, step in enumerate(fix_steps, 1):
            lines.append(f"### Step {i}: {step.get('step', '')}")
            if step.get("cli_command"):
                lines.append(f"")
                lines.append("```bash")
                lines.append(step["cli_command"])
                lines.append("```")
            lines.append(f"")

    if frameworks:
        lines += [
            f"## Compliance Frameworks",
            f"",
            ", ".join(f"`{f}`" for f in frameworks),
            f"",
        ]

    citations = result.get("citations", [])
    if citations:
        lines += [f"## References & Citations", f""]
        for i, cite in enumerate(citations, 1):
            title = cite.get("title", "Reference")
            url = cite.get("url", "")
            source = cite.get("source", "")
            source_label = f" ({source})" if source else ""
            if url:
                lines.append(f"{i}. [{title}]({url}){source_label}")
            else:
                lines.append(f"{i}. {title}{source_label}")
        lines.append(f"")

    lines += [
        f"---",
        f"",
        f"*Report generated by [CloudGuard AI](https://github.com/samadmd786/cloudguard)*",
    ]

    return "\n".join(lines)



